# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        btn_style = """
            background-color: #CFCFCF; 
            border-radius: 2px; 
            padding: 5px; 
            margin-top: 10px;
            margin-bottom: 10px;
            margin-left: 5px;
            margin-right: 5px;
        """
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 600)
        MainWindow.setMinimumSize(QtCore.QSize(500, 700))
        MainWindow.setMaximumSize(QtCore.QSize(500, 700))
        MainWindow.setStyleSheet("background-color: white;")

        self.centralWidget = QtWidgets.QWidget(MainWindow)
        self.centralWidget.setObjectName("centralWidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralWidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 500, 700))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(10, 10, 10, 10)
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.pick_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.pick_label.setObjectName("pick_label")
        self.verticalLayout.addWidget(self.pick_label)
        self.pick_file_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.pick_file_btn.setObjectName("pick_file_btn")
        self.pick_file_btn.setStyleSheet(btn_style)
        self.verticalLayout.addWidget(self.pick_file_btn)
        self.text_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.text_label.setObjectName("text_label")
        self.verticalLayout.addWidget(self.text_label)
        self.text_input = QtWidgets.QPlainTextEdit(self.verticalLayoutWidget)
        self.text_input.setObjectName("text_input")
        self.verticalLayout.addWidget(self.text_input)
        self.go_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        self.go_btn.setObjectName("go_btn")
        self.go_btn.setStyleSheet(btn_style)
        self.verticalLayout.addWidget(self.go_btn)
        self.progress_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget)
        self.progress_bar.setProperty("value", 24)
        self.progress_bar.setObjectName("progress_bar")
        self.verticalLayout.addWidget(self.progress_bar)
        self.result_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.result_label.setObjectName("result_label")
        self.verticalLayout.addWidget(self.result_label)
        MainWindow.setCentralWidget(self.centralWidget)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Определитель авторства"))
        self.pick_label.setText(_translate("MainWindow", "Папка с текстами авторов:"))
        self.pick_file_btn.setText(_translate("MainWindow", "Выбрать папку"))
        self.text_label.setText(_translate("MainWindow", "Текст, авторство которого нужно установить:"))
        self.go_btn.setText(_translate("MainWindow", "Начать анализ"))
        self.result_label.setText(_translate("MainWindow", ""))
